#!/usr/bin/env sh

# Builds image by copying treesitter parsers from prior jllacuna/nvim image
# Useful when you want to make some config changes and need a fast build
docker build --platform linux/amd64 -t jllacuna/nvim --target cached --progress plain .
